Create component-reference.md
o3de/sig-docs-community pull request #36
Opened 2022-03-08 22:48 UTC by chanmosq

This purpose of this PR is to move the component reference template from the website to the SIG Docs and Community repository. This PR is a fast-follow fix for the [PR #1415 in o3de.org](https://github.com/o3de/o3de.org/pull/1415)(merged) and depends on [PR #1472 in o3de.org](https://github.com/o3de/o3de.org/pull/1472)(open). 

As addressed by this [comment](https://github.com/o3de/o3de.org/pull/1415#discussion_r807384109) in PR #1415 in `o3de.org`. 

> @[sptramer](https://github.com/sptramer) sptramer [21 days ago](https://github.com/o3de/o3de.org/pull/1415#discussion_r807384109)
>
> Recommend removing this from the website and that we host a "templates" subsection for the SIG, where this can go and live. Will still do the review here, and we can accept this PR as-is and then make a fast-follow to post on the SIG repo and directly link to GitHub.

>@[chanmosq](https://github.com/chanmosq) chanmosq [20 days ago](https://github.com/o3de/o3de.org/pull/1415#discussion_r808503511)
>
> Sounds good to me. I'll leave as is and fast follow with a PR to remove the template from the website, add it to o3de/sig-docs-community, and update the links.

2022-03-08 23:52 UTC, FiniteStateGit requested changes
Just incorporating a few changes from the original PR.  These must have been hiding somewhere, I couldn't even find the edit where we changed request/notification to method. :shrug:

2022-03-08 23:52 UTC, FiniteStateGit commented on doc-templates/component-reference.md
> +title: \[Component Name] Component
```suggestion
title: [Component Name] Component
```

2022-03-08 23:52 UTC, FiniteStateGit commented on doc-templates/component-reference.md
> +| Property | Description | Value | default |
```suggestion
| Property | Description | Value | Default |
```

2022-03-08 23:52 UTC, FiniteStateGit commented on doc-templates/component-reference.md
> +| Request Name | Description | Parameter | Return | Scriptable |
```suggestion
| Method Name | Description | Parameter | Return | Scriptable |
```

2022-03-08 23:52 UTC, FiniteStateGit commented on doc-templates/component-reference.md
> +| Request Name | Description | Parameter | Return | Scriptable |
```suggestion
| Method Name | Description | Parameter | Return | Scriptable |
```

2022-03-08 23:57 UTC, chanmosq commented
@FiniteStateGit Thanks for recalling those updates here! Pushed the changes.

2022-03-09 00:04 UTC, FiniteStateGit approved these changes

2022-03-09 00:14 UTC, willihay approved these changes

2022-03-09 00:14 UTC, merged