Template for website reviewer nominations.
o3de/sig-docs-community pull request #79
Opened 2022-11-19 00:37 UTC by sptramer

Feedback welcome to address the open question of how one becomes a reviewer of the website and how they maintain that status.

2022-11-21 21:52 UTC, willihay commented
Any reason not to edit the [existing template](https://github.com/o3de/sig-docs-community/blob/main/.github/ISSUE_TEMPLATE/reviewer-maintainer-nomination.md) instead of creating a YAML file template?

2022-11-21 22:15 UTC, willihay commented on .github/ISSUE_TEMPLATE/website-reviewer.yaml
> +        **Maintaing status:** <???>
How about:
```suggestion
        **Maintaining status:** Once engaged in a review, promptly reply to any follow-up questions regarding your feedback. SIG chairpersons can remove the approval of this role, at their discretion, from reviewers who consistently fail to reply to questions regarding their feedback, or who have been inactive for an extended period of time during which reviews have been requested of the group.
```

2022-12-02 20:01 UTC, chanmosq requested changes

2022-12-06 00:40 UTC, chanmosq commented on .github/ISSUE_TEMPLATE/website-reviewer.yaml
> +        **Maintaining status:** Serve in the reviewer rotation as required. Serving in the review rotation requires an initial review of the submission,
NIt: Add a space here
```suggestion

        **Maintaining status:** Serve in the reviewer rotation as required. Serving in the review rotation requires an initial review of the submission,
```

2022-12-06 00:42 UTC, chanmosq commented on .github/ISSUE_TEMPLATE/website-reviewer.yaml
> +      label: Nominee GitHub username
Suggested in other nomination forms. Recommend doing it here too for consistency
```suggestion
      label: Nominee's GitHub username
```

2022-12-06 00:44 UTC, chanmosq approved these changes
Looks good! Left a few small suggestions, nothing blocking. Approving.

2022-12-07 21:02 UTC, merged